CMAKE_MINIMUM_REQUIRED( VERSION 2.8.12 )

SET( WGTF_FOUND 1 )
SET( WGTF_VERSION_MAJOR )
SET( WGTF_VERSION_MINOR )
SET( WGTF_VERSION_PATCH )
SET( WGTF_VERSION_TWEAK )

GET_FILENAME_COMPONENT( WGTF_SOURCE ${CMAKE_CURRENT_LIST_DIR}/../src ABSOLUTE )
SET( WGTF_INCLUDE_DIRS ${WGTF_SOURCE}/core/lib )
SET( WGTF_CORE_LIBRARIES core_wgtf_app )

ADD_SUBDIRECTORY( ${WGTF_SOURCE} wgtf )

FUNCTION( WGTF_USE _TARGET )
	TARGET_INCLUDE_DIRECTORIES( ${_TARGET} PUBLIC ${WGTF_INCLUDE_DIRS} )
	TARGET_LINK_LIBRARIES( ${_TARGET} PUBLIC ${WGTF_CORE_LIBRARIES} )
ENDFUNCTION()
